### ISSUE TITLE
Explain Sinks

### ISSUE THREAD

**Issue by qjhart** [ucd-cws/calvin-network-data#46]
@ucd-cws/hobbes , there were renewed questions about sinks.  We need to add the description of how they are treated into the documentation of how the conversion from calvin to Hobbes is working.  However,  this is a review of what was previously discussed.  The gist of this is that in Hobbes, sinks are not defined as separate nodes, but instead as a part of object.  This is more like how inflows are currently done, which was the analogy used.   The difference being that sinks can be assigned to both nodes or links.  The following diagram describes how this is currently being done in the import. 

![Conversion Image](https://docs.google.com/drawings/d/1il_tXxVTseaoo4tP9AJSF9h2Ep2wby8BWltR1C32fAw/pub?w=883&h=778)

[Sink Conversion Diagram](https://docs.google.com/drawings/d/1il_tXxVTseaoo4tP9AJSF9h2Ep2wby8BWltR1C32fAw/edit?usp=sharing)

In the GitHUB repo, sinks are a directory of the node or link.  The format is setup so that you can have multiple sinks on a single object, but none do yet.  We do however, need to link back to the current output in order to do proper book-keeping on our water balance, and that is not done yet.  We need to verify how sinks are named in PRMBuilder.

**Comment by msdogan** [comment]
I have a fairly simple suggestion for the sink representation in Hobbes. Sinks have several meanings in CALVIN. They can represent local depletion, canal loss, calibration flow, local demand, or end of the model. But basically we use them to take flow out of the system. In Hobbes, a sink is not represented as a node. My suggestion is that instead of determining if the node is junction or has associated properties, whenever there is a node with sink, add a sink that specific node. This will eliminate sinks to links in current Hobbes set up. It does not require adding or deleting nodes when there is a sink. That way it would be much closer to CALVIN's representation and we can easily show output results. When there is a sink attached to a node, we can add a sink link and show properties and outputs in that link.

**Comment by qjhart** [comment]
This table shows the number of removed sinks and some indication of where they are moved to

| item | nodes | links | delete |
| --- | --- | --- | --- |
| Original | 1183 | 1636 |  |
| Removed Non-Junction Node Sinks | 1149 | 1602 | 34 |
| Removed Link Sinks | 1080 | 1533 | 50+19 |
| Removed Junction Node Sinks | 1062 | 1515 | 18 |
| Removed Junction Calibration Inflows and Sinks | 1062 | 1515 | 0 |
| Removed NonJunction Calibration Inflows and Sinks | 1062 | 1514 | 1 |
| Removed Calibration Nodes | 1057 | 1514 | 5 |

**Comment by qjhart** [comment]
This table shows the origin type of the sinks that are removed.

| type | count |
| --- | --- |
| Agricultural Demand | 4 |
| Groundwater Storage | 1 |
| Junction | 68 |
| Surface Storage | 2 |
| Urban Demand | 12 |
| Water Treatment | 15 |
