### ISSUE TITLE
PRM Names and Labels

### ISSUE THREAD

**Issue by msdogan** [ucd-cws/calvin-network-data#49]
There is a ten character limit in PRM name field in Microsoft Access database. So, sometimes PRM names are different than their labels in the database. I thought it is something built-in but I saw that it was intentionally limited in Microsoft Access to 10 character. I am planning to change the character limit (increase maybe) and make PRM and Label names the same to make pre and post-processing easier. Do you foresee any problem with that? New naming convention eliminate "-" from node names and we will use "_" instead of space or ":"

**Comment by qjhart** [comment]
@msdogan,  Your issue worked great :), I'm not sure why you didn't see it.

The HEC PRM docs identify that as a limit, because of the fixed field size for the IDNODE identifiers for the input.  The HEC-PRM docs also imply that it's a limit in DSS files, but that not the case.  Let's look at a node with a 10 char value `HSU103AC13` for example. 

Here's everywhere in the generated PRI file where that node is used.

``` bash
grep HSU103AC13 S08I49.pri

NODE      HSU103AC13                    
LINK      DIVR      C13       HSU103AC131.000                         198.1
QI        A=S08I37 B=C13-HSU103AC13 C=FLOW_DIV(KAF) D= E=1MON F= 
LINK      DIVR      HSU103AC13HSR101    0.850                         
QI        A=S08I37 B=HSU103AC13-HSR101 C=FLOW_DIV(KAF) D= E=1MON F= 
LINK      DIVR      HSU103AC13A103A     1.000                         
QI        A=S08I37 B=HSU103AC13-A103A C=FLOW_DIV(KAF) D= E=1MON F= 
```

See the two lower links.  The source node runs right into the destination node.  If the PRMName was longer I think the HECPRM code will die.  @jrmerz  and I have been discussing how to get around this, because I agree it's a big pain, but we don't agree on how to do that, see for example #29.

I will close, but open if that's not correct.
