### ISSUE TITLE
Updated CALVIN Database

### ISSUE THREAD

**Issue by msdogan** [ucd-cws/calvin-network-data#51]
I have updated Node Names (and PRM Names), Link Names, and Inflow Name based on our naming convention. Now we use "-" only for links to connect two nodes, and "-" is eliminated from Node Names. Here is the link to updated CALVIN Engine (Database): 

X:\calvin\CALVIN_PP_Update\0.CALVIN_Engine_10272015 VP_MSD

There is a few more changes we have made in the past weeks in addition to naming:
- New operating costs for all surface pumping plants (Plants start with "PMP")
- New cost curves for some pumping plants
- Updated names for nodes, links, and inflows
- Updated node description for C28 and C29
- Node "D76a" is removed from the database since we had no use for it.

Please let me know if there is any issue with the updated database. If you are ok with changes, I can the model and provide you with output DSS file.

**Comment by qjhart** [comment]
@msdogan Sounds good. I checked it out, and I can programmatically change the name on this side, (for the node locations), and everything looks good.  Minor PRMName change EXTRedding => EXT_Reddin and INT as well.  But yes, let's get that output run.  Then reassign this issue to me.

**Comment by qjhart** [comment]
Also, be sure to give it a good version name.

**Comment by msdogan** [comment]
Yes, I renamed Urban Redding as EXT_Reddin and INT_Reddin just to be consistent with other urban labels, although I had to eliminate "g" at the end. Here is the link to the updated CALVIN run. It's named as S09I05.
X:\calvin\CALVIN_PP_Update\Runs\S09I05

**Comment by qjhart** [comment]
@msdogan so I've been looking at the sinks a bit more, and I have some questions about some of the output data.  I see a number of sinks (mostly on WWP) that seem to have sinks, but no flows in the output.  

```
  prmname      
```

---

 WWP205-Sink_G19
 WWP208-Sink_G23
 WWP209-Sink_G24
 WWP301-SinkG25
 WWP304-SinkG26
 WWP502-Sink_G33
 WWP504-Sink_G37
 WWP505-Sink_G40
 WWP506-Sink_G44
 WWP507-Sink_G45
 WWP509-Sink_G48
 WWP511-Sink_G50
 WWP406-Sink_SBSLO
 WWP501-Sink_G30
 WWP503-Sink_WWP50
 WWP508-Sink_WWTP5

These get added to the WWP as sinks to those nodes, but with no flow.

| prmname | description | type |
| --- | --- | --- |
| WWP503 |  | NOB |
| WWP507 | SW Discharge to ?? | NOB |
| WWP501 |  | NOB |
| WWP208 | Contra Costa | NOB |
| WWP508 |  | NOB |
| WWP511 | SW Discharge to Ocean | NOB |
| WWP502 | SW Discharge to ?? | NOB |
| WWP504 | SW Discharge to Ocean | NOB |
| WWP205 | Napa Solano | NOB |
| WWP209 | East Bay MUD | NOB |
| WWP509 | SW discharge to Ocean | NOB |
| WWP505 | SW Discharge to evap | NOB |
| WWP301 | San Francisco waste | NOB |
| WWP506 | SW Discharge to ocean via local streams | NOB |
| WWP304 | Santa Clara waste | NOB |

Similarly,the sink

```
  prmname      
```

---

 C62-Sink_C62

Has no flow.  Finally, the WWP406 gets assigned to the wrong location, because the type for that node doesn't match the others. 

| prmname | type |
| --- | --- |
| ... | ... |
| WWP401 | Water Treatment |
| WWP402 | Junction |
| WWP403 | Water Treatment |
| WWP405 | Water Treatment |
| WWP406 | Junction |
| WWP407 | Water Treatment |
| ... | ... |

| prmname | description | type |
| --- | --- | --- |
| INT_SB_SLO-WWP406 | SB-SLO outflow to ocean | NOB |
| C62-C64 | Friant-Kern Canal Losses | EQT |

**Comment by qjhart** [comment]
@msdogan also, there is one calibration node with flow still.  CN2-N201

| prmname | ymd | val |
| --- | --- | --- |
| CN2-N201 | 1924-09-30 | 6.604 |
| CN2-N201 | 1924-10-31 | 5.239 |
| CN2-N201 | 1931-09-30 | 4.348 |
| CN2-N201 | 1931-10-31 | 6.691 |
| CN2-N201 | 1988-09-30 | 3.108 |
| CN2-N201 | 1988-10-31 | 5.719 |

**Comment by qjhart** [comment]
@msdogan  There seem to be two DSS filename mismatches: 
The value for UpperBoundPathname = _/HEXT2014/HXI305_EXT: CVPM12/FLOW_UBT(KAF)-TARG//1MON/EB SOUTH UPDATE/_
 doesn't match the DSS file for link HXI305-Ext_CVPM12.

And the Constrained Flow pathname for link 'N201-Sink_N201'
/HEXT2014/N201_SINK N201/FLOW_LOC(KAF)//1MON/CALSIM - D290+D292/ is not found in the DSS file

**Comment by msdogan** [comment]
@qjhart First I am going to start with Sinks. I have checked a few of sinks (WWP205-Sink, WWP208-Sink, WWP209-Sink, and C62-Sink_C62) but there seems to be some flow in the output file (S09I05.DSS). These are mostly discharges to ocean (end of model), so there is no bound. CALVIN dynamically decides how much to discharge.

C62-Sink represents canal losses on Friant-Kern Canal. Yes it is a constrained flow (EQT). I gues based on your sink representation, it was assigned to link C62-C64.

I am going to update WWP402 and WWP406. Their type should be "water treatment plant node" instead of junction.

For calibration flows, yes I added those to make mass balance work. It's on Bear River watershed. I tried all other methods but without those calibration flows, results got infeasible. So, I ended up adding some calibration flow in some months.

For the pathname on link HXI305-EXT_CVPM12. Is what is not matching part B information? If so, we should have this for other ag and urban regions as well. Because I only updated node names and labels and link labels. I did not update paths that match the DSS file. But it would take some time but I can try if it is needed.

For N201-Sink_N201, I was able to locate /HEXT2014/N201_SINK N201/FLOW_LOC(KAF)//1MON/CALSIM - D290+D292/ in S09I05TS.DSS file. Would there be another problem?
