### ISSUE TITLE
File path error while cloning

### ISSUE THREAD

**Issue by msdogan** [ucd-cws/calvin-network-data#69]
GitHub gives following error while cloning calvin-network-data repository. I checked the file (sources/calvin120/Appendix G: Groundwater.doc) and it is in the repo but not sure why it is happening. @nickrsan Do you have any easy fix?

![Capture](https://user-images.githubusercontent.com/14085662/89626794-9982a900-d8a2-11ea-93dd-84112b40bfc0.PNG)

**Comment by nickrsan** [comment]
Hi Mustafa,

@mlmaskey and I had encountered this issue as well, and I was pretty sure I knew what it was, but hadn't resolved it. The Appendix G filename was only valid on Unix systems (Mac/Linux) since it had a colon in the name. I renamed the file and recommitted it and it should clone fine now since the issue was on file checkout and not the actual storage of the versions. Please give it a try and let me know if it works for you.

**Comment by msdogan** [comment]
@nickrsan it worked, thanks!
